export const defaultTextFields = [
  {
    id: 1,
    label: "Título",
    value: "CERTIFICADO",
    x: 370,
    y: 100,
    fontSize: 36,
    isDragging: false,
  },
  {
    id: 2,
    label: "Subtítulo",
    value: "de Conclusão",
    x: 370,
    y: 150,
    fontSize: 24,
    isDragging: false,
  },
  {
    id: 3,
    label: "Nome",
    value: "William Ardito",
    x: 370,
    y: 250,
    fontSize: 28,
    isDragging: false,
  },
  {
    id: 4,
    label: "Empresa",
    value: "COMPANY NAME",
    x: 370,
    y: 300,
    fontSize: 18,
    isDragging: false,
  },
  {
    id: 5,
    label: "Descrição",
    value:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo magna aliqua.",
    x: 200,
    y: 370,
    fontSize: 14,
    isDragging: false,
    width: 400,
  },
  {
    id: 6,
    label: "Data",
    value: "12.04.2022",
    x: 200,
    y: 450,
    fontSize: 16,
    isDragging: false,
  },
  {
    id: 7,
    label: "Assinatura",
    value: "Dr. K. Doe",
    x: 580,
    y: 450,
    fontSize: 16,
    isDragging: false,
  },
];

export const defaultProgramContentFields = [
  {
    id: 1,
    label: "Título da Página 2",
    value: "CONTEÚDO PROGRAMÁTICO",
    x: 320,
    y: 60,
    fontSize: 24,
    isDragging: false,
  },
  {
    id: 2,
    label: "Módulo 1",
    value: "1. Introdução aos conceitos básicos",
    x: 100,
    y: 120,
    fontSize: 16,
    isDragging: false,
  },
  {
    id: 3,
    label: "Módulo 2",
    value: "2. Desenvolvimento de habilidades avançadas",
    x: 100,
    y: 160,
    fontSize: 16,
    isDragging: false,
  },
  {
    id: 4,
    label: "Módulo 3",
    value: "3. Aplicação prática dos conhecimentos",
    x: 100,
    y: 200,
    fontSize: 16,
    isDragging: false,
  },
  {
    id: 5,
    label: "Módulo 4",
    value: "4. Avaliação e certificação",
    x: 100,
    y: 240,
    fontSize: 16,
    isDragging: false,
  },
  {
    id: 6,
    label: "Carga Horária",
    value: "Carga Horária Total: 40 horas",
    x: 100,
    y: 300,
    fontSize: 16,
    isDragging: false,
  },
  {
    id: 7,
    label: "Período",
    value: "Período de Realização: 01/03/2022 a 30/03/2022",
    x: 100,
    y: 340,
    fontSize: 16,
    isDragging: false,
  },
];
